' t9.bas -- T9 predictive text entry on the Intellivision keypad.
'
' From intv-keyboard-experiment, which built it to be lifted into exactly
' this kind of host. The Gmail Intellivision client wants it next, so it
' stays a module with a stable contract rather than something welded into
' the calendar: what changed on the way in is the memory map and two bugs,
' both marked PORT: below.
'
' Requires, from this host, ahead of it in the INCLUDE order:
'   constants.bas  KEYPAD_*/DISC_*, VAL_ROW0/VAL_ROWS/VAL_CELLS, SCREEN_COLS
'   input.bas      in_poll
'   screen.bas     g_ent_draw/g_ent_append/g_ent_backspace, COL_*, the
'                  g_len/g_ch/#ge_dst/#g_max entry contract
'   fujinet.bas    the DIM of fn_ok
' and t9dict.bas (generated by tools/mkdict.py) INCLUDEd LAST in the
' program -- its ASM ORGs would misplace anything assembled after it.
'
' The dictionary lives at fixed addresses and is read with PEEK: IntyBASIC
' is single-pass, so labels defined in that last include cannot be
' referenced from here. THESE THREE MUST MATCH tools/mkdict.py's
' --pool-org and --index-org, which the Makefile passes; nothing checks
' the agreement, and a mismatch reads plausible garbage rather than
' failing.
    CONST T9D_CHARS = $D800       ' letter pool, 2 ASCII chars/word, high first
    CONST T9D_META  = $B520       ' +0 word count, +1 max word length
    CONST T9D_INDEX = $B522       ' char offset of word i; count+1 entries

' PORT: the cart-RAM scratch this module claims (SC_T9_STACK, SC_T9_DIGITS)
' is declared in constants.bas now, not here. The experiment had it at
' $9500-$95FF, which in this host lands on top of SC_LINEBUF ($9520) and the
' head of SC_DETAIL ($95A0); it moved to the 256-byte hole reserved at $92A0,
' which fits it exactly. t9_poll went the same way -- its scripted-input hook
' is in in_poll now, so every screen is scriptable and not just this one.

' Letter -> keypad digit, 'a'..'z'. Data is safe here: the program's
' opening GOTO main never lets execution fall into an include.
t9_l2d:
    DATA 2,2,2,3,3,3,4,4,4,5,5,5,6,6,6,7,7,7,7,8,8,8,9,9,9,9

' Multi-tap cycles (ASCII), one entry per press of the same key:
'   0: " 0"   1: ".,:/-_@'?!1"   2-9: letters then the digit itself
t9_mtcyc:
    DATA 32,48
    DATA 46,44,58,47,45,95,64,39,63,33,49
    DATA 97,98,99,50
    DATA 100,101,102,51
    DATA 103,104,105,52
    DATA 106,107,108,53
    DATA 109,110,111,54
    DATA 112,113,114,115,55
    DATA 116,117,118,56
    DATA 119,120,121,122,57
' Offset of key k's cycle in t9_mtcyc; 11 entries, so the length of
' cycle k is t9_mtoff(k+1) - t9_mtoff(k).
t9_mtoff:
    DATA 0,2,13,17,21,25,29,33,38,42,47

    DIM t9_c, t9_d, t9_pp
    DIM #t9_wi, #t9_off, #t9_w


' ---------------------------------------------------------------------------
' t9_char_at: #t9_off (absolute char offset into the pool) -> t9_c, the
' lowercase-ASCII character stored there.
' ---------------------------------------------------------------------------
t9_char_at: PROCEDURE
    #t9_w = PEEK(T9D_CHARS + #t9_off / 2)
    IF (#t9_off AND 1) = 0 THEN
        #t9_w = #t9_w / 256
    ELSE
        #t9_w = #t9_w AND 255
    END IF
    t9_c = #t9_w
END

' ---------------------------------------------------------------------------
' t9_digit_at: word #t9_wi, character position t9_pp -> t9_d, the T9
' digit (2-9) of that character, or 0 if the word is shorter than
' t9_pp+1 characters. 0 sorts below every real digit, which is exactly
' the comparison the range narrowing needs: words that ran out of
' characters stay at the low end of the range.
' ---------------------------------------------------------------------------
t9_digit_at: PROCEDURE
    #t9_off = PEEK(T9D_INDEX + #t9_wi) + t9_pp
    IF #t9_off >= PEEK(T9D_INDEX + #t9_wi + 1) THEN
        t9_d = 0
    ELSE
        #t9_w = PEEK(T9D_CHARS + #t9_off / 2)
        IF (#t9_off AND 1) = 0 THEN
            #t9_w = #t9_w / 256
        ELSE
            #t9_w = #t9_w AND 255
        END IF
        t9_d = t9_l2d(#t9_w - 97)
    END IF
END

' ---------------------------------------------------------------------------
' Word-in-progress state. The candidate range [#t9_lo,#t9_hi) covers the
' dictionary words whose digit string starts with the t9_p digits typed
' so far; because the dictionary is sorted by digit string, it is always
' one contiguous run, and the t9_ncand words whose digit string is
' EXACTLY the typed digits (frequency-ordered) sit at its front.
' ---------------------------------------------------------------------------
    DIM t9_p, t9_cd, t9_cand, t9_ncand, t9_ok
    DIM #t9_lo, #t9_hi, #t9_a, #t9_b, #t9_m, #t9_nlo, #t9_nhi

    CONST T9_MAX_DIGITS = 15      ' range-stack depth - 1 (16 x 4-byte slots)
    CONST T9_NCAND_CAP  = 12      ' stop counting exact matches past this

t9_reset_word: PROCEDURE
    #t9_lo = 0
    #t9_hi = PEEK(T9D_META)
    t9_p = 0
    t9_cand = 0
    t9_ncand = 0
END

' ---------------------------------------------------------------------------
' t9_narrow: [#t9_nlo,#t9_nhi) = the words in [#t9_lo,#t9_hi) whose
' digit at position t9_p is t9_cd. Two binary searches; t9_digit_at's
' 0-for-short-words keeps exhausted words at the low end.
' ---------------------------------------------------------------------------
t9_narrow: PROCEDURE
    t9_pp = t9_p
    ' First word with digit >= t9_cd ...
    #t9_a = #t9_lo
    #t9_b = #t9_hi
    WHILE #t9_a < #t9_b
        #t9_m = (#t9_a + #t9_b) / 2
        #t9_wi = #t9_m
        GOSUB t9_digit_at
        IF t9_d < t9_cd THEN
            #t9_a = #t9_m + 1
        ELSE
            #t9_b = #t9_m
        END IF
    WEND
    #t9_nlo = #t9_a
    ' ... and the first with digit > t9_cd, searched only above #t9_nlo.
    #t9_b = #t9_hi
    WHILE #t9_a < #t9_b
        #t9_m = (#t9_a + #t9_b) / 2
        #t9_wi = #t9_m
        GOSUB t9_digit_at
        IF t9_d <= t9_cd THEN
            #t9_a = #t9_m + 1
        ELSE
            #t9_b = #t9_m
        END IF
    WEND
    #t9_nhi = #t9_a
END

' ---------------------------------------------------------------------------
' t9_count_exact: t9_ncand = words at the front of the range whose digit
' string is exactly the typed digits (their digit t9_p is 0 = past end),
' capped at T9_NCAND_CAP.
' ---------------------------------------------------------------------------
t9_count_exact: PROCEDURE
    t9_ncand = 0
    t9_pp = t9_p
    #t9_wi = #t9_lo
    WHILE #t9_wi < #t9_hi AND t9_ncand < T9_NCAND_CAP
        GOSUB t9_digit_at
        IF t9_d <> 0 THEN EXIT WHILE
        t9_ncand = t9_ncand + 1
        #t9_wi = #t9_wi + 1
    WEND
END

' ---------------------------------------------------------------------------
' t9_try_digit: try to extend the word with digit t9_cd (2-9).
' t9_ok = 1 and the state advances, or t9_ok = 0 and NOTHING changes --
' a digit that leads to an empty range (no word continues that way) is
' simply rejected, so the user can never type into a dead end.
' The outgoing range is stacked in cart RAM so t9_pop_digit is O(1).
' ---------------------------------------------------------------------------
t9_try_digit: PROCEDURE
    t9_ok = 0
    IF t9_p >= T9_MAX_DIGITS THEN RETURN
    GOSUB t9_narrow
    IF #t9_nlo >= #t9_nhi THEN RETURN
    t9_p = t9_p + 1
    POKE SC_T9_DIGITS + t9_p - 1, t9_cd
    POKE SC_T9_STACK + t9_p * 4, #t9_nlo AND 255
    POKE SC_T9_STACK + t9_p * 4 + 1, #t9_nlo / 256
    POKE SC_T9_STACK + t9_p * 4 + 2, #t9_nhi AND 255
    POKE SC_T9_STACK + t9_p * 4 + 3, #t9_nhi / 256
    #t9_lo = #t9_nlo
    #t9_hi = #t9_nhi
    t9_cand = 0
    GOSUB t9_count_exact
    t9_ok = 1
END

' ---------------------------------------------------------------------------
' t9_pop_digit: undo the last digit (Clear). Restores the previous range
' from the cart-RAM stack; popping the last digit resets the word.
' ---------------------------------------------------------------------------
t9_pop_digit: PROCEDURE
    IF t9_p = 0 THEN RETURN
    t9_p = t9_p - 1
    IF t9_p = 0 THEN
        GOSUB t9_reset_word
    ELSE
        #t9_lo = (PEEK(SC_T9_STACK + t9_p * 4) AND 255) + (PEEK(SC_T9_STACK + t9_p * 4 + 1) AND 255) * 256
        #t9_hi = (PEEK(SC_T9_STACK + t9_p * 4 + 2) AND 255) + (PEEK(SC_T9_STACK + t9_p * 4 + 3) AND 255) * 256
        t9_cand = 0
        GOSUB t9_count_exact
    END IF
END

' ===========================================================================
' The interactive entry UI. Contract mirrors kbd.bas's grid_entry: the
' caller sets #ge_dst (cart-RAM buffer) and #g_max (its size INCLUDING
' the NUL; must be the 16-bit variable it is) and primes the buffer --
' NUL at offset 0 for a fresh field, or existing NUL-terminated text to
' edit. GOSUB t9_entry blocks (WAIT loop inside) until keypad ENTER,
' then fn_ok = 1 and g_len holds the length; the buffer is mutated live
' and always NUL-terminated. Committed words are lowercase ASCII.
'
' Screen footprint: rows 0-2 value window (via kbd.bas g_ent_draw;
' pending word recolored yellow, or blue when it is only a dictionary
' prefix), row 3 candidate strip, row 11 key hints + mode indicator.
' Rows 4-10 are never touched -- they belong to the caller.
'
' Buffer invariant throughout: [0,t9_fix) = committed text, then the
' t9_p letters of the displayed pending word; g_len = t9_fix + t9_p.
' Committing a word is just t9_fix = g_len.
' ===========================================================================
    DIM t9_fix, t9_flash, t9_mode, t9_i, t9_j, t9_pw, t9_pk
    DIM t9_mtkey, t9_mti, t9_mtn, t9_mtbase, t9_mtlim
' PORT: t9_mtleft counts the multi-tap timeout DOWN, one per frame, where the
' experiment kept a 16-bit #t9_mtstart snapshot of FRAME and subtracted. The
' entry loop already runs exactly once per frame, so a countdown says the same
' thing in an 8-bit slot -- and 16-bit slots are what this host is short of.
' It also drops a latent FRAME-wraparound case the subtraction had.
    DIM t9_mtleft

    ' T9_STRIP_ROW moved to constants.bas: bar.bas reads it.
    CONST T9_FLASH_FRAMES = 8
    CONST T9_MT_NONE = 255

t9_entry: PROCEDURE
    g_len = 0
    WHILE (g_len < #g_max - 1) AND ((PEEK(#ge_dst + g_len) AND 255) <> 0)
        g_len = g_len + 1
    WEND
    t9_fix = g_len
    t9_flash = 0
    t9_mtkey = T9_MT_NONE
    ' Every field opens in T9. Leaving t9_mode alone made an ABC excursion --
    ' or a spurious one, back when a keystroke could flip it -- outlive the
    ' field it was wanted in, and the next form after that.
    t9_mode = 0
    t9_mtlim = 40
    IF NTSC THEN t9_mtlim = 48
    GOSUB t9_reset_word
    GOSUB g_ent_draw
    GOSUB t9_draw_strip
    GOSUB t9_draw_mode

    DO WHILE 1
        WAIT
        GOSUB in_poll

        IF t9_flash > 0 THEN
            t9_flash = t9_flash - 1
            IF t9_flash = 0 THEN
                GOSUB g_ent_draw
                GOSUB t9_recolor_pending
                GOSUB t9_draw_strip
            END IF
        END IF

        ' Multi-tap timeout: the pending character locks in.
        IF t9_mtkey <> T9_MT_NONE THEN
            t9_mtleft = t9_mtleft - 1
            IF t9_mtleft = 0 THEN
                t9_mtkey = T9_MT_NONE
                t9_fix = g_len
                GOSUB g_ent_draw
            END IF
        END IF

        IF in_key = KEYPAD_ENTER THEN
            t9_mtkey = T9_MT_NONE
            GOSUB t9_commit
            fn_ok = 1
            EXIT DO
        END IF

        IF in_btn <> 0 THEN
            t9_mtkey = T9_MT_NONE
            IF t9_mode = 0 THEN
                GOSUB t9_commit
                t9_mode = 1
            ELSE
                t9_fix = g_len
                GOSUB g_ent_draw
                t9_mode = 0
                GOSUB t9_reset_word
                GOSUB t9_draw_strip
            END IF
            GOSUB t9_draw_mode
            ' The mode test below is the NEXT statement, so without this the
            ' same frame's keypress would be handled by the mode just switched
            ' into rather than the one it was typed in. Same reason, and the
            ' same gesture, as the in_key clear in st_form.bas's do_form.
            in_key = KEYPAD_NONE
        END IF

        IF t9_mode = 0 THEN
            ' --- T9 predictive mode ---
            ' Any key but the punctuation key ends a punctuation cycle.
            '
            ' PORT: when one was actually running, t9_fix has to advance with
            ' it. t9_mt_press leaves the character it just placed PENDING
            ' (t9_fix = g_len - 1) so a repeat press can overwrite it in place.
            ' Clearing t9_mtkey alone ends the cycle but leaves t9_fix one
            ' short, and the letter this keypress is about to start writes at
            ' #ge_dst + t9_fix -- on top of the punctuation. Typing 8 4 3, then
            ' 1, then 8 inside the ~0.8s timeout turned "the." into "thet".
            '
            ' The t9_mtkey test around it is not optional, and the first
            ' version of this fix left it out: with no cycle running, t9_fix =
            ' g_len says "commit the pending word", so EVERY digit committed
            ' what was on screen and started again. Typing "meeting" gave
            ' "nofoffmeetmeetimeetinmeeting".
            IF in_key < KEYPAD_NONE AND in_key <> 1 THEN
                IF t9_mtkey <> T9_MT_NONE THEN
                    t9_mtkey = T9_MT_NONE
                    t9_fix = g_len
                END IF
            END IF
            IF in_key >= 2 AND in_key <= 9 THEN GOSUB t9_key_digit
            IF in_key = KEYPAD_0 THEN
                GOSUB t9_commit
                g_ch = 32
                GOSUB g_ent_append
                t9_fix = g_len
            END IF
            IF in_key = 1 THEN
                ' Punctuation: commit the word, then multi-tap key 1.
                GOSUB t9_commit
                t9_cd = 1
                GOSUB t9_mt_press
            END IF
            IF in_key = KEYPAD_CLEAR THEN GOSUB t9_key_clear

            IF in_disc = DISC_DOWN AND t9_ncand > 1 THEN
                t9_cand = t9_cand + 1
                IF t9_cand >= t9_ncand THEN t9_cand = 0
                GOSUB t9_write_pending
            END IF
            IF in_disc = DISC_UP AND t9_ncand > 1 THEN
                IF t9_cand = 0 THEN t9_cand = t9_ncand
                t9_cand = t9_cand - 1
                GOSUB t9_write_pending
            END IF
        ELSE
            ' --- multi-tap (ABC) mode ---
            IF in_key <= 9 THEN
                t9_cd = in_key
                GOSUB t9_mt_press
            END IF
            IF in_key = KEYPAD_CLEAR THEN
                t9_mtkey = T9_MT_NONE
                GOSUB g_ent_backspace
                t9_fix = g_len
            END IF
        END IF
    LOOP
END

' ---------------------------------------------------------------------------
' t9_mt_press: multi-tap press of key t9_cd (0-9). The same key inside
' the timeout cycles the pending character in place; anything else locks
' the previous character and starts a new one. Serves both ABC mode and
' the T9-mode punctuation key.
' ---------------------------------------------------------------------------
t9_mt_press: PROCEDURE
    IF t9_mtkey = t9_cd AND t9_mtleft > 0 THEN
        t9_mti = t9_mti + 1
        IF t9_mti >= t9_mtn THEN t9_mti = 0
        POKE #ge_dst + g_len - 1, t9_mtcyc(t9_mtbase + t9_mti)
        GOSUB g_ent_draw
        GOSUB t9_mt_recolor
    ELSE
        t9_fix = g_len
        IF g_len >= #g_max - 1 THEN
            t9_mtkey = T9_MT_NONE
            GOSUB t9_flash_err
            RETURN
        END IF
        t9_mtkey = t9_cd
        t9_mtbase = t9_mtoff(t9_cd)
        t9_mtn = t9_mtoff(t9_cd + 1) - t9_mtbase
        t9_mti = 0
        g_ch = t9_mtcyc(t9_mtbase)
        GOSUB g_ent_append
        t9_fix = g_len - 1
        GOSUB t9_mt_recolor
    END IF
    t9_mtleft = t9_mtlim
END

' t9_mt_recolor: highlight the pending multi-tap character (the last
' buffer character) in the value window.
t9_mt_recolor: PROCEDURE
    #t9_a = 0
    IF g_len > VAL_CELLS - 1 THEN #t9_a = g_len - (VAL_CELLS - 1)
    IF g_len - 1 >= #t9_a THEN
        #t9_m = g_len - 1 - #t9_a
        #t9_w = (#BACKTAB(#t9_m) AND $FFF8) + COL_HILIGHT
        #BACKTAB(#t9_m) = #t9_w
    END IF
END

' ---------------------------------------------------------------------------
' t9_key_digit: handle keypad 2-9 in T9 mode. A digit that would
' overflow the buffer or lead to an empty range is rejected with a
' flash; otherwise the pending word is rewritten in place.
' ---------------------------------------------------------------------------
t9_key_digit: PROCEDURE
    IF g_len >= #g_max - 1 THEN
        GOSUB t9_flash_err
        RETURN
    END IF
    t9_cd = in_key
    GOSUB t9_try_digit
    IF t9_ok = 0 THEN
        GOSUB t9_flash_err
    ELSE
        GOSUB t9_write_pending
    END IF
END

' ---------------------------------------------------------------------------
' t9_key_clear: Clear = un-type the last digit of the pending word, or
' plain backspace into committed text once no word is pending.
' ---------------------------------------------------------------------------
t9_key_clear: PROCEDURE
    IF t9_p > 0 THEN
        GOSUB t9_pop_digit
        IF t9_p = 0 THEN
            g_len = t9_fix
            POKE #ge_dst + g_len, 0
            GOSUB g_ent_draw
            GOSUB t9_draw_strip
        ELSE
            GOSUB t9_write_pending
        END IF
    ELSE
        GOSUB g_ent_backspace
        t9_fix = g_len
    END IF
END

' ---------------------------------------------------------------------------
' t9_commit: freeze the displayed pending word into the committed text
' and reset the word state. Safe to call with nothing pending.
' ---------------------------------------------------------------------------
t9_commit: PROCEDURE
    t9_fix = g_len
    GOSUB t9_reset_word
    GOSUB g_ent_draw
    GOSUB t9_draw_strip
END

' ---------------------------------------------------------------------------
' t9_write_pending: copy the selected candidate's first t9_p letters
' into the buffer after the committed text, NUL-terminate, and redraw
' the value window, pending recolor and candidate strip. Only called
' with t9_p >= 1. When t9_ncand = 0 the range's first word lends its
' prefix (shown dim -- it is a completion hint, not an exact match).
' ---------------------------------------------------------------------------
t9_write_pending: PROCEDURE
    #t9_wi = #t9_lo + t9_cand
    #t9_off = PEEK(T9D_INDEX + #t9_wi)
    FOR t9_i = 0 TO t9_p - 1
        GOSUB t9_char_at
        POKE #ge_dst + t9_fix + t9_i, t9_c
        #t9_off = #t9_off + 1
    NEXT t9_i
    g_len = t9_fix + t9_p
    POKE #ge_dst + g_len, 0
    GOSUB g_ent_draw
    GOSUB t9_recolor_pending
    GOSUB t9_draw_strip
END

' ---------------------------------------------------------------------------
' t9_recolor_pending: repaint the pending word's cells in the value
' window -- yellow for an exact match, green for a prefix-only
' completion. g_ent_draw drew them tan like committed text.
'
' PORT: the prefix colour was COL_DIM. In this host the value window sits on
' the blue header run, so blue-on-blue vanished; CS_GREEN reads there, stays
' clearly apart from the yellow exact match, and is inside the 0-7 a GROM
' card's foreground can express in colour-stack mode.
' ---------------------------------------------------------------------------
t9_recolor_pending: PROCEDURE
    IF t9_p = 0 THEN RETURN
    #t9_a = 0
    IF g_len > VAL_CELLS - 1 THEN #t9_a = g_len - (VAL_CELLS - 1)
    t9_j = COL_HILIGHT
    IF t9_ncand = 0 THEN t9_j = CS_GREEN
    #t9_b = t9_fix
    IF #t9_b < #t9_a THEN #t9_b = #t9_a
    WHILE #t9_b < g_len
        #t9_m = #t9_b - #t9_a
        #t9_w = (#BACKTAB(#t9_m) AND $FFF8) + t9_j
        #BACKTAB(#t9_m) = #t9_w
        #t9_b = #t9_b + 1
    WEND
END

' ---------------------------------------------------------------------------
' t9_draw_strip: candidate strip on row 3. With exact matches:
' "n/m" then up to three candidates at columns 4/10/16 (5 chars each,
' the selected one highlighted). With none: the range's first word as a
' dim completion preview. Empty when no word is pending.
' ---------------------------------------------------------------------------
' PORT: the blanking loop keeps bit 13. It used to store a bare 0, which
' zeroes the colour-stack advance bit along with the card and the colour -- and
' in this host the strip's row 3 carries the bit that starts the form's content
' run, so opening a field dropped every row below it one stack position. AND
' CS_ADVANCE blanks exactly as much as the 0 did and is host-agnostic: it
' preserves whatever the host stamped there, or nothing if it stamped nothing.
t9_draw_strip: PROCEDURE
    FOR t9_i = 0 TO SCREEN_COLS - 1
        #BACKTAB(T9_STRIP_ROW * SCREEN_COLS + t9_i) = #BACKTAB(T9_STRIP_ROW * SCREEN_COLS + t9_i) AND CS_ADVANCE
    NEXT t9_i
    IF t9_p = 0 THEN RETURN

    IF t9_ncand > 0 THEN
        t9_j = t9_cand + 1 + 16
        IF t9_cand + 1 > 9 THEN t9_j = 11 + 16      ' '+' card is 11
        ' PORT: this one cell is column 0 of the strip row, which is where a
        ' host that uses the colour stack starts its content run -- so it is
        ' OR'd in rather than stored over. The blanking loop above left the
        ' cell holding nothing but that bit, if the host set one.
        #BACKTAB(T9_STRIP_ROW * SCREEN_COLS) = #BACKTAB(T9_STRIP_ROW * SCREEN_COLS) OR (t9_j * 8 + COL_NORMAL)
        #BACKTAB(T9_STRIP_ROW * SCREEN_COLS + 1) = 15 * 8 + COL_NORMAL
        t9_j = t9_ncand + 16
        IF t9_ncand > 9 THEN t9_j = 11 + 16
        #BACKTAB(T9_STRIP_ROW * SCREEN_COLS + 2) = t9_j * 8 + COL_NORMAL
        ' Up to three candidates at columns 4, 10, 16.
        FOR t9_j = 0 TO 2
            IF t9_j < t9_ncand THEN
                #t9_wi = #t9_lo + t9_j
                t9_pw = COL_DIM
                IF t9_j = t9_cand THEN t9_pw = COL_HILIGHT
                #t9_a = T9_STRIP_ROW * SCREEN_COLS + 4 + t9_j * 6
                GOSUB t9_strip_word
            END IF
        NEXT t9_j
    ELSE
        #t9_wi = #t9_lo
        t9_pw = COL_DIM
        #t9_a = T9_STRIP_ROW * SCREEN_COLS + 4
        GOSUB t9_strip_word
    END IF
END

' t9_strip_word: word #t9_wi at BACKTAB position #t9_a, color t9_pw,
' truncated to 5 characters (15 for the lone completion preview).
'
' PORT: the row-end bound is new. The third slot starts at column 16, so a
' 5-character candidate wrote columns 16-20 -- and column 20 of row 3 IS
' column 0 of row 4, which here is the form's TITLE field. It needed three
' exact matches sharing a digit string AND a word of 5+ letters, which the
' experiment's own 2000-word list happens never to produce; a different word
' list makes it live (74273 -> share/phase/shape at 4000). Bounding the write
' to the row fixes every slot at once rather than special-casing the third.
t9_strip_word: PROCEDURE
    #t9_off = PEEK(T9D_INDEX + #t9_wi)
    #t9_b = PEEK(T9D_INDEX + #t9_wi + 1)
    t9_pk = 5
    IF t9_ncand = 0 THEN t9_pk = 15
    #t9_m = (T9_STRIP_ROW + 1) * SCREEN_COLS
    WHILE #t9_off < #t9_b AND t9_pk > 0 AND #t9_a < #t9_m
        GOSUB t9_char_at
        #BACKTAB(#t9_a) = (t9_c - 32) * 8 + t9_pw
        #t9_a = #t9_a + 1
        #t9_off = #t9_off + 1
        t9_pk = t9_pk - 1
    WEND
END

' ---------------------------------------------------------------------------
' t9_flash_err: rejected input -- flash the strip and the cursor block
' red for a few frames; the entry loop restores them when it expires.
' ---------------------------------------------------------------------------
t9_flash_err: PROCEDURE
    FOR t9_i = 0 TO SCREEN_COLS - 1
        #t9_w = #BACKTAB(T9_STRIP_ROW * SCREEN_COLS + t9_i)
        IF #t9_w <> 0 THEN
            #t9_w = (#t9_w AND $FFF8) + COL_ERROR
            #BACKTAB(T9_STRIP_ROW * SCREEN_COLS + t9_i) = #t9_w
        END IF
    NEXT t9_i
    #t9_a = 0
    IF g_len > VAL_CELLS - 1 THEN #t9_a = g_len - (VAL_CELLS - 1)
    IF g_len - #t9_a < VAL_CELLS THEN
        #BACKTAB(g_len - #t9_a) = (95 - 32) * 8 + COL_ERROR
    END IF
    t9_flash = T9_FLASH_FRAMES
END

' ---------------------------------------------------------------------------
' t9_draw_mode: key hints and mode indicator on row 11.
' ---------------------------------------------------------------------------
' PORT: the hints start at column 1, not 0, and are COL_NORMAL rather than
' COL_DIM. Column 0 of the hint row is where a host that uses the colour stack
' puts its last advance bit -- this one does -- and PRINT writes a bare
' card*8+colour that would wipe it. COL_DIM is CS_BLUE, which is invisible on
' the blue run that bit produces.
t9_draw_mode: PROCEDURE
    PRINT AT screenpos(1,11) COLOR COL_NORMAL, "0:SPC CLR:DEL   "
    IF t9_mode = 0 THEN
        PRINT AT screenpos(17,11) COLOR COL_NORMAL, " T9"
    ELSE
        PRINT AT screenpos(17,11) COLOR COL_NORMAL, "ABC"
    END IF
END
