#!/usr/bin/env bash
# build.sh -- assemble the Astrocade Google Calendar client with zmac.
#
# Usage: ./build.sh            (DEMO=1 ./build.sh for the static mock screens)
#
# Output: build/gcal.bin, a 20K banked APPBANK image (firmware protocol
# v2): the 8K window plus three 4K pages, mailbox pages clear, "FUJI" claim
# signature at 0x1CFC so the mailbox stays alive when the image is booted
# over the network. The layout contract is enforced by
# tools/checkrom.py --banked; tools/checksize.py prints the per-region
# budget table.
#
# Environment:
#   DEMO=1              assemble the static mock screens instead of the app
#   ZMAC=path           assembler override
#   FUJI_PICO=path      cartridge bring-up tree, only used as the last place
#                       to look for zmac (default
#                       ~/Workspace/fujinet-firmware/pico/astrocade)
#
# Self-contained the way netcat and the game ports are: the layout checker
# is vendored in tools/ and fujilib.inc / HVGLIB.H live here, so a build
# needs no particular branch of the firmware tree checked out. Those are
# copies of the bring-up's testrom/ files -- keep them in step.

set -euo pipefail
cd "$(dirname "$0")"

# The banked image: the 8K window plus the form, settings and splash pages.
IMAGE=$((8192 + 3*4096))
CLAIM_OFF=$((0x1CFC))

FUJI_PICO=${FUJI_PICO:-$HOME/Workspace/fujinet-firmware/pico/astrocade}

find_zmac() {
    if [ -n "${ZMAC:-}" ]; then
        echo "$ZMAC"
        return
    fi
    if command -v zmac >/dev/null 2>&1; then
        echo zmac
        return
    fi
    if [ -x "$HOME/Workspace/zmac-1.3/zmac" ]; then
        echo "$HOME/Workspace/zmac-1.3/zmac"
        return
    fi
    local tree="$FUJI_PICO/tools/zmac"
    if [ -d "$tree" ]; then
        if [ ! -x "$tree/zmac" ]; then
            touch "$tree/zmac.c"    # keep it newer than zmac.y: no yacc wanted
            make -C "$tree" zmac >/dev/null
        fi
        echo "$tree/zmac"
        return
    fi
    echo "build.sh: no zmac found; put one on PATH or set ZMAC=" >&2
    exit 1
}

ZMAC=$(find_zmac)
mkdir -p build

# Build flags. DEMO=1 assembles the static mock screens instead of the app.
{
    echo "; generated by build.sh -- do not edit"
    echo "DEMO    EQU     ${DEMO:-0}"
} > build/flags.inc

# zmac 1.3 resolves INCLUDE against the cwd; assemble from here.
"$ZMAC" -o build/gcal.raw -x build/gcal.lst gcal.asm

size=$(wc -c < build/gcal.raw)
if [ "$size" -gt "$IMAGE" ]; then
    echo "build.sh: gcal is $size bytes, over the $IMAGE image" >&2
    exit 1
fi

# Pad to the full image (zmac zero-fills the gaps between ORGs, the
# mailbox pages included), stamp the claim.
{
    cat build/gcal.raw
    head -c $((IMAGE - size)) /dev/zero
} > build/gcal.bin
printf 'FUJI' | dd of=build/gcal.bin bs=1 seek=$CLAIM_OFF \
    conv=notrunc status=none
rm -f build/gcal.raw

python3 tools/checkrom.py --banked build/gcal.bin
python3 tools/checksize.py build/gcal.lst
