#!/usr/bin/env python3
"""mkdict.py -- generate t9dict.bas, the ROM dictionary for t9.bas.

Input: a frequency-ordered word list, one word per line (most frequent
first).  Lines not matching ^[a-z]{1,15}$ are dropped; duplicates keep
their first (highest-frequency) occurrence; the first --count survivors
are used.

Output: an IntyBASIC include with three ROM tables, sorted by T9 digit
string (abc=2 ... wxyz=9), lexicographic, ties broken by frequency rank
(Python's stable sort).  That ordering is what makes the runtime cheap:

  * every typed digit prefix selects ONE contiguous [lo,hi) range;
  * a word whose digit string is a strict prefix of another's sorts
    first, so exact-length matches sit at the front of the range,
    already in frequency order.

Tables sit at FIXED addresses -- t9.bas reads them with PEEK on CONST
addresses rather than label references, because this include must be the
last thing in the program (its ASM ORGs would misplace anything after
it) and IntyBASIC is a single-pass compiler, so labels defined here are
not usable earlier in the program:
  --pool-org   t9_chars  the letter pool, packed 2 lowercase-ASCII chars
                         per 16-bit word, HIGH byte first, zero-padded
  --index-org  t9_meta   2 entries: word count, max word length
               t9_index  count+1 entries, the CHARACTER offset of word i
                         into the pool; length(i) = index(i+1) - index(i)

The letter->digit map is static and lives in t9.bas, not here.

THE ORGs ARE PARAMETERS, NOT CONSTANTS. The t9demo host had $A000, $D000
and $F000 all to itself; a real host does not. gcal, for one, already has
code at $D000 and $F000, so a generator that hardcoded them would quietly
assemble the index on top of st_week and the epilogue on top of st_event.
Whoever owns the memory map passes the addresses in, and --epilogue-org
may be omitted entirely when the host would rather place the IntyBASIC
epilogue itself.

The caller is also responsible for the addresses being free and for the
tables fitting: --pool-limit and --index-limit are the ceilings this
checks against, and they default to nothing more than the pool and index
segments the demo used.

Every run re-parses its own output and diffs the decoded words against
the input selection -- a build that emits a bad table fails loudly.
"""

import argparse
import re
import sys

# Default ceilings (16-bit words), matching the t9demo host's map. The
# pool segment is $A000-$BFFF on paper, but GRAM is aliased at
# $B800-$BFFF on the Intellivision bus (jzIntv maps it there too), so
# only $A000-$B7FF is safe for cart ROM. Override both with
# --pool-limit / --index-limit when the host's map differs.
INDEX_SEG_WORDS = 4096   # $D000-$DFFF
POOL_SEG_WORDS = 6144    # $A000-$B7FF

WORD_RE = re.compile(r"^[a-z]{1,15}$")

L2D = {}
for letters, digit in (("abc", 2), ("def", 3), ("ghi", 4), ("jkl", 5),
                       ("mno", 6), ("pqrs", 7), ("tuv", 8), ("wxyz", 9)):
    for ch in letters:
        L2D[ch] = digit


def digit_string(word):
    return "".join(str(L2D[c]) for c in word)


def load_words(path, count):
    seen = set()
    words = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            w = line.strip()
            if not WORD_RE.match(w) or w in seen:
                continue
            seen.add(w)
            words.append(w)
            if len(words) == count:
                break
    if not words:
        sys.exit(f"mkdict: no usable words in {path}")
    return words


def data_lines(values, fmt, per_line=10):
    for i in range(0, len(values), per_line):
        chunk = ",".join(fmt(v) for v in values[i:i + per_line])
        yield f"    DATA {chunk}"


def emit(words, source_path, out_path, opts):
    # Stable sort by digit string keeps frequency order within ties.
    ordered = sorted(words, key=digit_string)

    pool = "".join(ordered)
    index = [0]
    for w in ordered:
        index.append(index[-1] + len(w))

    n_index_words = len(index) + 2
    n_pool_words = (len(pool) + 1) // 2
    if n_index_words > opts.index_limit:
        sys.exit(f"mkdict: meta+index is {n_index_words} words, over the "
                 f"{opts.index_limit} allowed at ${opts.index_org:04X} -- "
                 f"reduce --count")
    if n_pool_words > opts.pool_limit:
        sys.exit(f"mkdict: letter pool is {n_pool_words} words, over the "
                 f"{opts.pool_limit} allowed at ${opts.pool_org:04X} -- "
                 f"reduce --count or use a shorter-worded list")

    padded = pool + ("\0" if len(pool) % 2 else "")
    pool_words = [(ord(padded[i]) << 8) | ord(padded[i + 1])
                  for i in range(0, len(padded), 2)]

    maxlen = max(len(w) for w in ordered)

    lines = [
        "' t9dict.bas -- GENERATED by tools/mkdict.py -- DO NOT EDIT",
        f"' Source: {source_path} ({len(words)} words kept, "
        f"max length {maxlen})",
        "' Sorted by T9 digit string; frequency rank breaks ties.",
        f"' Segments: pool ${opts.pool_org:04X} ({n_pool_words} words), "
        f"meta+index ${opts.index_org:04X} ({n_index_words} words)",
        "' t9.bas reads these via PEEK on T9D_CHARS/T9D_META/T9D_INDEX --",
        "' keep those CONSTs in step with the addresses above.",
        "",
        f"    ASM ORG ${opts.pool_org:04X}",
        "' Letter pool: 2 lowercase-ASCII chars per word, high byte first.",
        "t9_chars:",
    ]
    lines.extend(data_lines(pool_words, lambda v: f"${v:04X}", per_line=8))
    lines += [
        "",
        f"    ASM ORG ${opts.index_org:04X}",
        "' Word count, max word length.",
        "t9_meta:",
        f"    DATA {len(index) - 1},{maxlen}",
        "' Character offset of word i into t9_chars; count+1 entries.",
        "t9_index:",
    ]
    lines.extend(data_lines(index, str))
    if opts.epilogue_org is not None:
        lines += [
            "",
            "' Leave the epilogue (appended after this, the last include)",
            "' its own empty segment.",
            f"    ASM ORG ${opts.epilogue_org:04X}",
        ]
    else:
        lines += [
            "",
            "' No epilogue ORG: the host places the IntyBASIC epilogue, which",
            "' assembles immediately after the index above.",
        ]
    lines.append("")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return ordered


def parse_back(out_path):
    """Re-read the emitted file and decode the word list from its tables."""
    tables = {}
    current = None
    with open(out_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            m = re.match(r"^(t9_\w+):$", line)
            if m:
                current = tables.setdefault(m.group(1), [])
                continue
            if current is not None and line.startswith("DATA "):
                for tok in line[5:].split(","):
                    tok = tok.strip()
                    current.append(int(tok[1:], 16) if tok.startswith("$")
                                   else int(tok))
            elif line and not line.startswith("'") and current is not None:
                current = None

    chars, index = tables["t9_chars"], tables["t9_index"]
    pool = "".join(chr((w >> 8) & 0xFF) + chr(w & 0xFF) for w in chars)
    return [pool[index[i]:index[i + 1]] for i in range(len(index) - 1)]


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("wordlist", help="frequency-ordered word list")
    ap.add_argument("-o", "--output", required=True, help="output .bas file")
    ap.add_argument("--count", type=int, default=2000,
                    help="number of words to keep (default 2000)")

    def addr(text):
        return int(text.lstrip("$"), 16)

    ap.add_argument("--pool-org", type=addr, default=0xA000,
                    help="ROM address of the letter pool (default $A000)")
    ap.add_argument("--index-org", type=addr, default=0xD000,
                    help="ROM address of meta+index (default $D000)")
    ap.add_argument("--epilogue-org", type=addr, default=None,
                    help="trailing ASM ORG for the IntyBASIC epilogue; "
                         "omit to let the host place it")
    ap.add_argument("--pool-limit", type=int, default=POOL_SEG_WORDS,
                    help=f"max pool words (default {POOL_SEG_WORDS})")
    ap.add_argument("--index-limit", type=int, default=INDEX_SEG_WORDS,
                    help=f"max meta+index words (default {INDEX_SEG_WORDS})")
    args = ap.parse_args()

    words = load_words(args.wordlist, args.count)
    ordered = emit(words, args.wordlist, args.output, args)

    decoded = parse_back(args.output)
    if decoded != ordered:
        sys.exit("mkdict: self-verify FAILED -- emitted tables do not "
                 "decode back to the input selection")

    ds = [digit_string(w) for w in ordered]
    assert ds == sorted(ds), "mkdict: digit-string order violated"
    pool_w = (sum(len(w) for w in words) + 1) // 2
    index_w = len(words) + 3
    print(f"mkdict: {len(words)} words -> {args.output} "
          f"(pool {pool_w}/{args.pool_limit} words at ${args.pool_org:04X}, "
          f"meta+index {index_w}/{args.index_limit} words at "
          f"${args.index_org:04X}, maxlen {max(len(w) for w in words)}); "
          f"self-verify OK")


if __name__ == "__main__":
    main()
